/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Asignatura;
import modelo.Nota;
import modelo.Utilidades;

/**
 *
 * @author dainz
 */
public class VisualVistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VisualMainView
     */
    public VisualVistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreAsignatura = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        cmbAsig = new javax.swing.JComboBox<>();
        btnAgregarNota = new javax.swing.JButton();
        txtNota = new javax.swing.JTextField();
        txtPonderacion = new javax.swing.JTextField();
        lblNota = new javax.swing.JLabel();
        lblPonderacion = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblPonderacionTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDisplayPonderacionTotal = new javax.swing.JLabel();
        lblDisplayPromedio = new javax.swing.JLabel();
        btnCalcNecesario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("x/dainz");
        setResizable(false);

        lblNombreAsignatura.setText("Selecciona una asignatura: ");

        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nota", "Ponderacion ( % )"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNotas.setEnabled(false);
        tblNotas.setFocusable(false);
        tblNotas.setRequestFocusEnabled(false);
        tblNotas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblNotas);

        btnSave.setText("Guardar");

        cmbAsig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAsigActionPerformed(evt);
            }
        });

        btnAgregarNota.setText("Agregar");

        lblNota.setText("Nota:");

        lblPonderacion.setText("Ponderación:");

        lblPromedio.setText("Promedio:");

        lblPonderacionTotal.setText("Ponderación total:");

        jLabel1.setText("%");

        lblDisplayPonderacionTotal.setText("jLabel2");

        lblDisplayPromedio.setText("jLabel2");

        btnCalcNecesario.setText("Que nota necesito?");
        btnCalcNecesario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcNecesarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPonderacionTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDisplayPonderacionTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPromedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDisplayPromedio)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnCalcNecesario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPonderacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPonderacion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarNota))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblNombreAsignatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPonderacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarNota)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNota)
                    .addComponent(lblPonderacion)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPonderacionTotal)
                    .addComponent(lblPromedio)
                    .addComponent(lblDisplayPonderacionTotal)
                    .addComponent(lblDisplayPromedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcNecesario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAsigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAsigActionPerformed

    private void btnCalcNecesarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcNecesarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcNecesarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualVistaPrincipal().setVisible(true);
            }
        });
    }

    public void cargarAsignaturas() {
        this.cmbAsig.removeAllItems();

        for (Asignatura a : Utilidades.asignaturas) {

            ((JComboBox<String>) this.cmbAsig).addItem(a.getNombre());
        }

    }

    public void cargarNotas(Asignatura asig) {
        tblNotas.removeAll();
        String[] header = {"Nota", "Ponderacion ( % )"};
        DefaultTableModel tabla = new DefaultTableModel(header, 0);
        String[] datos = new String[2];
        for (Nota n : asig.getNotas()) {
            datos[0] = String.valueOf(n.getNota());
            datos[1] = String.valueOf(n.getPonderacion());
            tabla.addRow(datos);
        }
        tblNotas.setModel(tabla);
    }

    public void cargarPromedio(Asignatura asig) {
        this.lblDisplayPromedio.setText(String.valueOf(asig.getPromedio()));
        this.lblDisplayPonderacionTotal.setText(String.valueOf(asig.getPonderacionTotal()) + "%");
    }
    
    public void limpiarAgregarNota(){
        this.txtNota.setText("");
        this.txtPonderacion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNota;
    private javax.swing.JButton btnCalcNecesario;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAsig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDisplayPonderacionTotal;
    private javax.swing.JLabel lblDisplayPromedio;
    private javax.swing.JLabel lblNombreAsignatura;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblPonderacion;
    private javax.swing.JLabel lblPonderacionTotal;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPonderacion;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnCalcNecesario() {
        return btnCalcNecesario;
    }

    public JLabel getLblNombreAsignatura() {
        return lblNombreAsignatura;
    }

    public JTable getTblNotas() {
        return tblNotas;
    }

    public JComboBox<String> getCmbAsig() {
        return cmbAsig;
    }

    public JButton getBtnAgregarNota() {
        return btnAgregarNota;
    }

    public JLabel getLblDisplayPonderacionTotal() {
        return lblDisplayPonderacionTotal;
    }

    public JLabel getLblDisplayPromedio() {
        return lblDisplayPromedio;
    }

    public JTextField getTxtNota() {
        return txtNota;
    }

    public JTextField getTxtPonderacion() {
        return txtPonderacion;
    }

}
